version: '2.1'

services:
  database:
    image: postgres
    container_name: controle_ponto
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=controlePonto
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local